# fly.toml app configuration file generated for dot-proxy
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doh-proxy"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  adblock = "adblock.toml"
  family = "family.toml"
  freedom = "freedom.toml"
  paranoia = "paranoia.toml"

# adblock.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 1853
  processes = ["adblock"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 1853

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6

# adblock.quic.mydns.network
[[services]]
  protocol = "udp"
  internal_port = 1443
  processes = ["adblock"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 1443

# family.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 2853
  processes = ["family"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 2853

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6

# family.quic.mydns.network
[[services]]
  protocol = "udp"
  internal_port = 2443
  processes = ["family"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 2443

# freedom.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 3853
  processes = ["freedom"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 3853

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6

# freedom.quic.mydns.network
[[services]]
  protocol = "udp"
  internal_port = 3443
  processes = ["freedom"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 3443

# paranoia.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 4853
  processes = ["paranoia"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 4853

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 6

# paranoia.quic.mydns.network
[[services]]
  protocol = "udp"
  internal_port = 4443
  processes = ["paranoia"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 4443

[services.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 250