# fly.toml app configuration file generated for notarelay on 2023-06-30T22:48:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doh-proxy"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

# adblock.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 1853

  [[services.ports]]
    port = 1853

# family.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 2853

  [[services.ports]]
    port = 2853

# freedom.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 3853

  [[services.ports]]
    port = 3853

# paranoia.dot.mydns.network
[[services]]
  protocol = "tcp"
  internal_port = 4853

  [[services.ports]]
    port = 4853

[services.concurrency]
  type = "connections"
  hard_limit = 500
  soft_limit = 250

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "1s"
  restart_limit = 6
