[resolvers.family]
address = "https://family.mydns.network/dns-query?routedns"
protocol = "doh"

[groups.family-cache]
type = "cache"
resolvers = ["family"]
cache-negative-ttl = 3600
cache-answer-shuffle = "random"
backend = {type = "memory", size = 1000}

[listeners.family-dot]
address = "0.0.0.0:2853"
protocol = "dot"
resolver = "family-cache"
server-crt = "cloudflare.crt"
server-key = "cloudflare.key"