[resolvers.freedom]
address = "https://freedom.mydns.network/dns-query?routedns"
protocol = "doh"

[groups.freedom-cache]
type = "cache"
resolvers = ["freedom"]
cache-negative-ttl = 3600
cache-answer-shuffle = "random"
backend = {type = "memory", size = 1000}

[listeners.freedom-dot]
address = "0.0.0.0:3853"
protocol = "dot"
resolver = "freedom-cache"
server-crt = "cloudflare.crt"
server-key = "cloudflare.key"

[listeners.freedom-quic]
address = ":3443"
protocol = "doh"
transport = "quic"
resolver = "freedom-cache"
server-crt = "cloudflare.crt"
server-key = "cloudflare.key"